[package]
name = "rust_ray_tracer"
version = "0.1.0"
authors = ["Ben Axford <ben.axford@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
impl_ops = "0.1.1"
indicatif = "0.16.1"
rand = "0.8.0"
rayon = "1.5.0"
ultraviolet = "0.8.1"